const activityFeed = [ {type:"Fatigue",
			date:"July 30 2018",
			details:"Dad's heartbeat was abnormally high for 2 minute",
			id:"001",
			iconName: "heartbeat",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Sleep",
			date:"July 28 2018",
			details:"Dad got less than 5 hours of sleep last night",
			id:"002",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Fatigue",
			date:"July 28 2018",
			details:"Dad met his sleep goal last night!",
			id:"003",
			iconName: "heart",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 2018",
			details:"Dad experienced some abnormal heart beats at 8:52 am.",
			id:"004",
			iconName: "arrow-down",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"July 27 2018",
			details:"Dad reduced his overall risk factor by 3% since yesterday!",
			id:"005",
			iconName: "ios-walk",
			iconType: "ionicon",
			color: "gray"},
			{type:"Health",
			date:"July 25 2018",
			details:"Dad didn't meet his step goal yesterday. Is he getting out enough?",
			id:"006",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"July 24 2018",
			details:"Dad increased his overall risk factor by 2% from yesturday. Give him a call and see how he's feeling.",
			id:"007",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"July 22 2018",
			details:"Battery is low on Dad's fitbit.",
			id:"008",
			iconName: "battery-1",
			iconType: "font-awesome",
			color: "gray"},
		     ];

activityItem = {type:"Health",
                        date:"July 21 2018",
                        details:"Dad went for a 23 minute walk today. Remind him to keep it up!",
                        id:"010",
			iconName: "ios-walk",
			iconType: "ionicon",
			color: "tomato"};

export {activityFeed, activityItem};
