const activityFeed = [ {type:"Fatigue",
			date:"Jan 28 1990",
			details:"Dad had an event where something happened",
			id:"001",
			iconName: "newspaper-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Sleep",
			date:"June 28 1990",
			details:"Dad had another event where something happened",
			id:"002",
			iconName: "bathtub",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Fatigue",
			date:"June 29 1990",
			details:"Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"003",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Ok now we are doing great. Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"004",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Ok now we are doing great. Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"005",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Ok now we are doing great. Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"006",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Ok now we are doing great. Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"007",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Ok now we are doing great. Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"008",
			iconName: "newspaper-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Ok now we are doing great. Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"009",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
		     ];

activityItem = {type:"Health",
                        date:"June 50 1990",
                        details:"YO I AM AN ITEM. I AM THE NEWS NEWS IN THE HOUSE, HOLLA!!",
                        id:"010",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "tomato"};

export {activityFeed, activityItem};
