const activityFeed = [ {type:"Fatigue",
			date:"July 06 2018",
			details:"Dad's heartbeat was abnormally high for 2 minute",
			id:"001",
			iconName: "heartbeat",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Sleep",
			date:"July 07 2018",
			details:"Dad got less than 5 hours of sleep last night",
			id:"002",
			iconName: "bathtub",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Fatigue",
			date:"June 29 1990",
			details:"Dad met his sleep goal last night!",
			id:"003",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Dad experienced some abnormal heart beats at 8:52 am.",
			id:"004",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Dad reduced his overall risk factor by 3% since yesterday!",
			id:"005",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Dad didn't meet his step goal yesterday. Is he getting out enough?",
			id:"006",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Dad increased his overall risk factor by 2% from yesturday. Give him a call and see how he's feeling.",
			id:"007",
			iconName: "moon-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Ok now we are doing great. Dad had another event where something happened and this text is very long. Blah blah this is some real long text.",
			id:"008",
			iconName: "newspaper-o",
			iconType: "font-awesome",
			color: "gray"},
			{type:"Health",
			date:"June 50 1990",
			details:"Battery is low on Dad's fitbit.",
			id:"009",
			iconName: "battery-1",
			iconType: "font-awesome",
			color: "gray"},
		     ];

activityItem = {type:"Health",
                        date:"June 50 1990",
                        details:"Dad went for a 23 minute walk today. Remind him to keep it up!",
                        id:"010",
			iconName: "newspaper-o",
			iconType: "font-awesome",
			color: "tomato"};

export {activityFeed, activityItem};
